jobs:
  test_nvidia_smi:
    <<: *gpu
    steps:
      - checkout
      - run: nvidia-smi
  flexflow_build_test:
    <<: *cpu_py39
    steps:
      - checkout
      - run: sudo apt install -y protobuf-compiler
      - run: pip install pytest
      - run: pip install torch
      - run: pip install onnx
      - run: export FF_HOME=$PWD
      - run: cd python
      - run: make
workflows:
  nvidia:  
    jobs:
      - test_nvidia_smi
      - flexflow_build_test
