version: 2.1

cpu_py39: &cpu_py39
  docker:
    - image: circleci/python:3.9
  resource_class: medium

gpu: &gpu
  environment:
    CUDA_VERSION: "10.1"
  machine:
    image: ubuntu-1604-cuda-10.1:201909-23
  resource_class: gpu.large

jobs:
  test_nvidia_smi:
    <<: *gpu
    steps:
      - checkout
      - run: nvidia-smi
  onnx_test:
    <<: *cpu_py39
    steps:
      - run: pip install pytest
      - run: ls

workflows:
  nvidia:  
    jobs:
      - test_nvidia_smi
      - onnx_test
