version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    gpu: &gpu
    environment:
      CUDA_VERSION: "10.1"
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.large
    steps:
      - checkout
      - run: nvidia-smi
      - run: pip install pytest
      - run: python -m pytest
workflows:
  nvidia:  
    jobs:
      - build-and-test
